### ISSUE TITLE
Field.ButtonOption 按钮选中状态文案颜色、背景色高亮 禁止失效

### ISSUE THREAD

**Issue by zl612** [24jieqi/react-native-xiaoshu#58]
![image](https://github.com/24jieqi/react-native-xiaoshu/assets/29365019/7acb34f6-efae-4a85-84e2-eb974fd2c30d)
![image](https://github.com/24jieqi/react-native-xiaoshu/assets/29365019/81c758a7-f94a-4eb6-a35f-84522781dd17)
设置了activeHighlight false 属性 照常失效
组件版本 0.3.21

**Comment by onlyling** [comment]
<img width="368" alt="image" src="https://github.com/24jieqi/react-native-xiaoshu/assets/9999765/81804df3-1b54-4029-80d7-02d1dd67b5c2">

是想要达到这样的效果？

**Comment by zl612** [comment]
跟普通按钮一样   选中不会有高亮选中效果

**Comment by zl612** [comment]
![image](https://github.com/24jieqi/react-native-xiaoshu/assets/29365019/5d322499-06dc-4467-b1cb-30718eb2256d)

**Comment by onlyling** [comment]
两个截图的样式表现是一致的。

如果想达到点击后没有选中的效果可以如下。

```tsx
const Demo = () => {
  return (
    <Field.ButtonOption
      title="快速输入"
      options={options}
      // 给一个 options 里不存在的值
      value={-1}
      onChange={(v) => {
        // 点击按钮响应回调，value 不更新，没有任何按钮激活
        console.log("v -> ", v);
      }}
    />
  );
};

```

**Comment by zl612** [comment]
增加这个    value={-1} 有用

会修复activeHighlight 这个属性的设置吗

**Comment by onlyling** [comment]
activeHighlight 应该是理解不同。

activeHighlight 的初衷是按钮激活的时候呈现不同样子。

<img width="272" alt="image" src="https://github.com/24jieqi/react-native-xiaoshu/assets/9999765/acafee07-582d-4cce-8712-a1645ddeacdc">

例如上面两组按钮分别是 active={true}&activeHighlight={true} 和 active={true}&activeHighlight={false} 状态的表现。

现在有一个小问题，activeHighlight 的描述是「选中状态文案颜色、背景色高亮」，现在只是对文案颜色做了处理。对于 `type="outline"` 的背景色不正确。

<img width="284" alt="image" src="https://github.com/24jieqi/react-native-xiaoshu/assets/9999765/961bdf66-c992-480c-982b-ff85e406e0da">

这组优化后的才达到「选中状态文案颜色、背景色高亮」。
