### ISSUE TITLE
benchmark/performance overview?

### ISSUE THREAD

**Issue by aboozaid** [24jieqi/react-native-xiaoshu#60]
I currently test the package using this benchmark guide [benchmark-repo](https://github.com/efstathiosntonas/react-native-style-libraries-benchmark) but it seems the render time of components I used from the package is much better than native itself.

Also the package increases the release apk by ~ 2MB in size if you have any idea to decrease that it would be appreciated.

I'm not sure about my benchmark test if I did it well or not by I hope you provide a one.

Thank you.

**Comment by onlyling** [comment]
No performance test cases.😬
[benchmark](https://github.com/24jieqi/react-native-xiaoshu/blob/next/example/app/pages/demo/benchmark.tsx)
This example is written with reference to benchmark-repo.
