### ISSUE TITLE
请问什么时候能推出黑夜模式呢

### ISSUE THREAD

**Issue by YuGer26** [24jieqi/react-native-xiaoshu#69]
目前没有夜间模式，导致很多组件的颜色需要通过主题定制的方式进行变化，但此方法也不尽人意，因为很多颜色并没有暴露出来，还需要进组件进行定制，我现在是用patch保存，但是改多了也不是长久之计

**Comment by onlyling** [comment]
可以参考 example 的[深色主题](https://github.com/24jieqi/react-native-xiaoshu/blob/main/example/app/contexts/theme.tsx)，在[入口文件](https://github.com/24jieqi/react-native-xiaoshu/blob/main/example/app/app.provider.tsx#L20)注入变量。

Expo 扫描查看 example 体验深色主题。

![](https://camo.githubusercontent.com/cb98b88b36f24fdad8fb755a33466f5095b81c4dcff624d9c84183c1132e95c4/68747470733a2f2f71722e6578706f2e6465762f6561732d7570646174653f736c75673d6578702670726f6a65637449643d36313065333132312d643038362d343438342d383032332d3133306463613739333765632667726f757049643d30633165303265642d316264642d343638622d383336312d653561356537633462306566)

**Comment by YuGer26** [comment]
const isThemeDark = useThemeDark(); 
  const customThemeVar = {
    // 定制基础颜色
    white: theme.bg,
    black: theme.reBg,
    gray_2: theme.gap,
    gray_8: theme.reBg,
    // 定制组件颜色
    button_border_radius: 18,
    button_l_font_size: "1rem",
    button_subtext_font_size: "1rem",
    button_l_height: 48,
    text_input_clearable_background_color: theme.buttonBg,
    text_input_clearable_size: 20,
    action_sheet_description_color: theme.miniText,
    dialog_background_color: theme.pageBg,
    dialog_footer_divider_color: theme.gap,
  };
  return (
    <Provider theme={[isThemeDark ? Theme.dark : undefined, customThemeVar]}>

**Comment by YuGer26** [comment]
<Provider theme={[isThemeDark ? Theme.dark : undefined, customThemeVar]}><App /></Provider>

**Comment by YuGer26** [comment]
此方式无法共存，如何把定制主题和dark共存呢

**Comment by onlyling** [comment]
```tsx
import { Provider, Theme } from "@fruits-chain/react-native-xiaoshu";
import React, { useMemo } from "react";

const customThemeVar = {
  // 定制基础颜色
  white: theme.bg,
  black: theme.reBg,
  gray_2: theme.gap,
  gray_8: theme.reBg,
  // 定制组件颜色
  button_border_radius: 18,
  button_l_font_size: "1rem",
  button_subtext_font_size: "1rem",
  button_l_height: 48,
  text_input_clearable_background_color: theme.buttonBg,
  text_input_clearable_size: 20,
  action_sheet_description_color: theme.miniText,
  dialog_background_color: theme.pageBg,
  dialog_footer_divider_color: theme.gap,
};

const App = () => {
  const isThemeDark = useThemeDark();
  const themeMerge = useMemo(() => {
    if (isThemeDark) {
      return {
        ...customThemeVar,
        ...Theme.dark,
        // TODO 细节颜色，例如 gray
        // TODO 或者把 customThemeVar 基础颜色去掉
      };

      return customThemeVar;
    }
  }, [isThemeDark]);

  return (
    <Provider theme={themeMerge}>
      <Todo />
    </Provider>
  );
};

```
