### ISSUE TITLE
可以去掉rc-field-form 吗？

### ISSUE THREAD

**Issue by lxzy-yun** [24jieqi/react-native-xiaoshu#73]
对表单输入型的组件只保留 UI 部分，form 逻辑部分分离出去，比如自己项目用 formily 等等，不是很想用rc-field-form

**Comment by onlyling** [comment]
完全可以，`Form` 组件只是对 rc-field-form 做了简单的分装，扩展了一些使用方法。`Form.Item` 负责校验逻辑，没有添加任何样式。

`Field` 相关组件是使用 `Cell` 组件对基础输入控件进行二次包装的产物，没有带任何校验逻辑。

如果工程使用了按需加载方式，也可以不安装 rc-field-form 库，使用基础输入控件配合其他表单组件使用。

**Comment by lxzy-yun** [comment]
嗯嗯，那就放心了
