### ISSUE TITLE
表单中，在Form的外面使用了react native 自带的组件ScrollView后无法使用clearable（无法清除输入框里面的内容）

### ISSUE THREAD

**Issue by jiaoxiaoyuan** [24jieqi/react-native-xiaoshu#75]
表单中，在Form的外面使用了react native 自带的组件ScrollView后无法使用clearable（无法清除输入框里面的内容）。
![WX20241014-182033](https://github.com/user-attachments/assets/e55cd0d1-ec06-4bbc-b3ac-ba001e6c9990)
![image](https://github.com/user-attachments/assets/0582f57d-37c8-4ffe-9415-4e9f78e37b31)

![WX20241014-182033](https://github.com/user-attachments/assets/19abed5d-2a61-4a18-8116-e6c356837f38)

**Comment by onlyling** [comment]
参考文档：[ScrollVIew - keyboardShouldPersistTaps](https://www.react-native.cn/docs/scrollview#keyboardshouldpersisttaps)

```jsx
<ScrollVIew keyboardShouldPersistTaps="handled"></ScrollVIew>
```

**Comment by jiaoxiaoyuan** [comment]
感谢。
