### ISSUE TITLE
Tree组件的TreeMultipleMode导入的时候报错

### ISSUE THREAD

**Issue by geeker-cmc** [24jieqi/react-native-xiaoshu#81]
![image](https://github.com/user-attachments/assets/581bca96-d03f-420c-979c-7887fa197163)

**Comment by onlyling** [comment]
暂时看不出来哪儿出问题了。

**Comment by onlyling** [comment]
```jsx
<Tree
  options={options}
  defaultValue={defaultValue}
  multiple
  multipleMode={Tree.MultipleMode.INDEPENDENT}
/>
```
在 web 端这样使用没有报错。[代码](https://github.com/onlyling/xiaoshu-web-demo/blob/main/src/pages/tree/index.tsx)

**Comment by geeker-cmc** [comment]
好的，这样没问题了，谢谢
